title: dulldesk
description: Self-taught secondary student programmer seeking to pursue a career in computer science
logo: /assets/img/logo.svg

plugins:
  - jekyll-seo-tag

collections:
  favicons:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

exclude: ["**/README.md", "README.md", "Gemfile*"]
