title: dulldesk
description: I'm Celeste Luo, a self-taught secondary student programmer seeking to pursue a career in computer science
logo: /assets/img/logo.svg
url: "https://dulldesk.github.io"

plugins:
  - jekyll-seo-tag

collections:
  favicons:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
      has_icons: false

sass:
  style: compressed

exclude: ["**/README.md", "README.md", "Gemfile*"]
