title: dulldesk
description: Celeste Luo - Computer Science student at the University of Waterloo
logo: /assets/img/logo.svg
url: "https://dulldesk.github.io"

theme_toggle: false

plugins:
  - jekyll-seo-tag
  - jemoji

collections:
  favicons:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
      has_icons: true

sass:
  style: compressed

exclude: ["**/README.md", "README.md", "Gemfile*",".git-blame-ignore-revs",".gitignore"]
